name: Build & Push Docker image to Container Registry and Deploy to DO apps

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      environment:
        required: true
        type: string
      deploy_app_id:
        required: false
        type: string
    secrets:
      do_token:
        required: true
      envs:
        required: false
    outputs:
      deploy_id:
        description: The digitalocean deploy id
        value: ${{ jobs.build-deploy.outputs.deploy_id }}

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    outputs:
      deploy_id: ${{ steps.deployment.outputs.deploy_id }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do_token }}

      - name: Login to registry
        run: doctl registry login

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        id: cache-layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-single-buildx-${{ inputs.environment }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-single-buildx-${{ inputs.environment }}

      - name: Create secrets file
        run: echo "${{ secrets.envs }}" >> /tmp/secrets.txt

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          builder: ${{ steps.buildx.outputs.name }}
          file: Dockerfile
          push: true
          tags: registry.digitalocean.com/animately/${{ inputs.name }}:${{ inputs.environment }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          secret-files: |
            "envs=/tmp/secrets.txt"

      - name: Clean up secrets file
        run: rm -f /tmp/secrets.txt

      - name: Determine deployment
        id: determine-deployment
        continue-on-error: true
        run: |
          if [ "${{ steps.cache-layers.outputs.cache-hit }}" == "true" ] | [ -z "${{ inputs.deploy_app_id }}" ]; then
            echo "::set-output name=deploy::0";
          else
            echo "::set-output name=deploy::1";
          fi

      - name: Deploy DO apps
        if: contains(steps.determine-deployment.outputs.deploy, '1')
        id: deployment
        timeout-minutes: 30
        run: |
          echo "Create deployment for app: ${{ inputs.deploy_app_id }}"
          deploy_id=$(doctl apps create-deployment ${{ inputs.deploy_app_id }} --format ID --no-header --wait)
          echo "::set-output name=deploy_id::$deploy_id"

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
