name: Destroy Review App

on:
  workflow_call:
    inputs:
      deploy_app_id:
        required: true
        type: string
      container_tag:
        required: true
        type: string
    secrets:
      do_token:
        required: true

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do_token }}

      - name: Login to registry
        run: doctl registry login

      - name: Delete app on digitalocean
        run: doctl apps delete ${{ inputs.deploy_app_id }} -f

      - name: Delete image on Container Registry
        run: |
          doctl registry repository delete-tag animately ${{ inputs.container_tag }} -f
          
