name: Destroy Review App

on:
  workflow_call:
    inputs:
      deploy_app_id:
        required: true
        type: string
      container_tag:
        required: true
        type: string
      service:
        required: true
        type: string

jobs:
  destroy:
    runs-on: self-hosted
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login to registry
        run: doctl registry login

      - name: Delete app on digitalocean
        continue-on-error: true
        run: doctl apps delete ${{ inputs.deploy_app_id }} -f

      - name: Delete image on Container Registry
        continue-on-error: true
        env:
          SERVICE: ${{ inputs.service }}
          TAG: ${{ inputs.container_tag }}
        run: |
          digest=$(doctl registry repository lt $SERVICE --format Tag,ManifestDigest | grep $TAG | grep -oEi 'sha256:.*')
          echo "Delete container with manifest: $digest"
          
          doctl registry repository dm $SERVICE $digest -f
        
