name: Generate review slug

on:
  workflow_call:
    outputs:
      slug:
        description: Get the review slug based on head ref
        value: ${{ jobs.generate-slug.outputs.slug }}

jobs:
  generate-slug:
    runs-on: self-hosted
    outputs:
      slug: ${{ steps.slug.outputs.slug }}
    steps:
      - name: Generate slug
        uses: rlespinasse/github-slug-action@v4
        with:
          short-length: 8
      - name: Generate outputs
        id: slug
        run: |
          echo "==> Slug: review-$GITHUB_HEAD_REF_SLUG"
          echo "::set-output name=slug::review-$GITHUB_HEAD_REF_SLUG"
