name: Update service spec

on:
  workflow_call:
    inputs:
      deploy_app_id:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      do_token:
        required: true
      service_spec:
        required: true

jobs:
  sync-spec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout administration
        uses: actions/checkout@v2
        with:
          repository: Animately/administration
          token: ${{ github.token }}

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do_token }}

      - name: Login to registry
        run: doctl registry login

      - name: Generate app-spec.json from doctl
        run: |
          doctl apps spec get ${{ inputs.deploy_app_id}} --format json > "$GITHUB_WORKSPACE/app-spec.json"

      - name: Generate service-spec.json from secrets
        run: echo '${{ secrets.service_spec }}' >> "$GITHUB_WORKSPACE/service-spec.json"

      - name: Apply new spec to digitalocean and redeploy
        run: |
          node scripts/spec-service.js ${{ inputs.service }} app-spec.json service-spec.json \
          | doctl apps update ${{ inputs.deploy_app_id }} --wait --spec -

      - name: Clean up
        run: |
          rm "$GITHUB_WORKSPACE/app-spec.json"
          rm "$GITHUB_WORKSPACE/service-spec.json"
