name: Update service spec

defaults:
  run:
    shell: bash -ieo pipefail {0}

on:
  workflow_call:
    inputs:
      deploy_app_id:
        required: true
        type: string
      service:
        required: true
        type: string
    secrets:
      do_token:
        required: true
      service_spec:
        required: true

jobs:
  sync-spec:
    runs-on: self-hosted
    steps:
      - name: Checkout administration
        uses: actions/checkout@v3
        with:
          repository: Animately/administration
          token: ${{ github.token }}

      - name: Install do-spec
        run: cd do-spec; npm install && npm install -g .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.do_token }}

      - name: Login to registry
        run: doctl registry login

      - name: Generate app-spec.json from doctl
        run: |
          doctl apps spec get ${{ inputs.deploy_app_id }} --format json > app-spec.json

      - name: Generate service-spec.json from secrets
        run: echo '${{ secrets.service_spec }}' >> service-spec.json

#      - name: Debug service
#        run: |
#          curl -X POST https://f769-92-64-174-116.ngrok.io -H 'Content-Type: application/json' --data "@service-spec.json"

      - name: Generate new spec-file
        run: |
          do-spec merge-service app-spec.json ${{ inputs.service }} service-spec.json > generated-phase-1-spec.json
          do-spec correct generated-phase-1-spec.json redirect-webflow,optimizer > generated-spec.json

#      - name: Debug app
#        run: |
#          curl -X POST https://48f9-92-64-174-116.ngrok.io -H 'Content-Type: application/json' --data "@generated-spec.json"

      - name: Apply new spec to digitalocean and redeploy
        run: |
          doctl apps update ${{ inputs.deploy_app_id }} --wait --spec generated-spec.json

      - name: Clean up
        run: |
          rm app-spec.json
          rm service-spec.json
          rm generated-phase-1-spec.json
          rm generated-spec.json
